# version: '3.8'

services:
  react-frontend:
    container_name: tmdb-app                # Nama container custom
    build:
      context: .                            # Path ke project (Dockerfile)
      dockerfile: Dockerfile
    image: ${IMAGE_NAME}:${IMAGE_TAG}       # Nama image custom
    ports:
      - "3000:3000"                         # Host:Container
    volumes:
      - .:/app                              # Bind mount kode
      - /app/node_modules                   # Hindari node_modules overwrite
    stdin_open: true
    tty: true
